---
enable_memcached: "yes"

# NOTE: Most memcached clients handle load-balancing via client side
# hashing (consistent or not) logic, so going under the covers and messing
# with things that the clients are not aware of is generally wrong
enable_haproxy_memcached: "no"

memcached_port: "11211"
memcache_security_strategy: "ENCRYPT"
