---
# TODO(dawudm) We should replace these two tasks with a task to check the port
# is free in precheck.yml in the D release
- name: Stop and remove containers for haproxy exporter containers
  become: true
  kolla_container:
    action: "stop_and_remove_container"
    common_options: "{{ docker_common_options }}"
    name: "prometheus_haproxy_exporter"
  when:
    - inventory_hostname in groups['loadbalancer']

- name: Removing config for haproxy exporter
  file:
    path: "{{ node_config_directory }}/prometheus-haproxy-exporter"
    state: "absent"
  become: true
  when:
    - inventory_hostname in groups['loadbalancer']

# TODO(mnasiadka): Remove this task after Gazpacho release
- name: Removing config for neutron-tls-proxy
  file:
    path: "{{ node_config_directory }}/haproxy/services.d/neutron-tls-proxy.cfg"
    state: "absent"
  become: true
  when:
    - inventory_hostname in groups['loadbalancer']

# TODO(mnasiadka): Remove this task in Gazpacho/2026.1 release
- name: Removing config for ironic-inspector
  file:
    path: "{{ node_config_directory }}/haproxy/services.d/ironic-inspector.cfg"
    state: "absent"
  become: true
  when:
    - inventory_hostname in groups['loadbalancer']

- import_tasks: deploy.yml
